// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AndenSemesterProjekt.Models
{
    public partial class PickupPoint
    {
        [Key]
        [Column("PickupPointID")]
        [StringLength(5)]
        public string PickupPointId { get; set; }
        [StringLength(10)]
        public string PickupTime { get; set; }
        [Required]
        [StringLength(50)]
        public string Adress { get; set; }
    }
}